# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (every 3 hours)
  schedule:
    - cron: "0 */3 * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      actions: read
      checks: write
    concurrency:
      group: metrics-update
      cancel-in-progress: true
    steps:
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/lockfiles') }}

      - name: Verify METRICS_TOKEN
        run: |
          if [ -z "${{ secrets.METRICS_TOKEN }}" ]; then
            echo "METRICS_TOKEN is not set!"
            exit 1
          else
            echo "METRICS_TOKEN is set."
          fi

      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: Cannomaly
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Phoenix
          plugin_gists: true
          plugin_habits: true
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: true
          plugin_habits_from: 200
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year
          plugin_lines: true
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_traffic: true

      - name: Commit & Push changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with GitHub Metrics' || echo "No changes to commit"
          git push
