name: GitHub Metrics

on:
  schedule:
    - cron: '0 */24 * * *'  # Runs every 6 hours
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_achievements: yes
          plugin_achievements_threshold: S
          config_timezone: UTC
          output: README.md
      - name: Commit & Push changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with GitHub Metrics' || echo "No changes to commit"
          git push
