# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics

on:
  # Schedule updates (every 3 hours)
  schedule:
    - cron: "0 */1 * * *"
  # Allows manual triggering of the workflow
  workflow_dispatch:
  # Triggers the workflow on pushes to master or main branches
  push:
    branches:
      - master
      - main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write        # Allows reading and writing repository contents
      issues: write          # Allows writing to issues
      pull-requests: write   # Allows writing to pull requests
      actions: read          # Allows reading action metadata
      checks: write          # Allows writing check runs

    concurrency:
      group: metrics-update
      cancel-in-progress: true

    steps:
      # 1. Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true  # Ensures that the GITHUB_TOKEN is available for pushing
          fetch-depth: 0             # Fetches all history for all branches and tags

      # 2. Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache
          key: ${{ runner.os }}-cache-${{ hashFiles('**/lockfiles') }}
          restore-keys: |
            ${{ runner.os }}-cache-

      # 3. Verify METRICS_TOKEN
      - name: Verify METRICS_TOKEN
        run: |
          if [ -z "${{ secrets.METRICS_TOKEN }}" ]; then
            echo "METRICS_TOKEN is not set!"
            exit 1
          else
            echo "METRICS_TOKEN is set."
          fi

      # 4. Generate Metrics
      - name: Generate Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: Cannomaly
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: America/Phoenix
          plugin_gists: true
          plugin_habits: true
          plugin_habits_charts_type: classic
          plugin_habits_days: 14
          plugin_habits_facts: true
          plugin_habits_from: 200
          plugin_isocalendar: true
          plugin_isocalendar_duration: full-year
          plugin_lines: true
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          plugin_traffic: true

      # 5. Commit & Push changes with Retry Mechanism
      - name: Commit & Push changes
        run: |
          git config --local user.name 'github-actions[bot]'
          git config --local user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'Update README with GitHub Metrics' || echo "No changes to commit"
          
          # Pull the latest changes from the remote main branch and rebase
          git pull --rebase origin main

          # Attempt to push the changes with up to 3 retries
          for i in {1..3}; do
            git push origin main && break || {
              echo "Push failed on attempt $i, retrying in 5 seconds..."
              sleep 5
            }
          done
          
          # Final push attempt
          git push origin main

      # 6. Notify on Workflow Failure
      - name: Notify on Failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
